
# execution nodes
CLEAR_BASICJSONPERSISTENCE = "CLEAR_BASICJSONPERSISTENCE"
RESET_BASICJSONPERSISTENCE = "RESET_BASICJSONPERSISTENCE"
READ_BASICJSONPERSISTENCE = "READ_BASICJSONPERSISTENCE"
READ_PERSISTENCE = "READ_PERSISTENCE"  # generic, shared


# interfaces
PERSISTENCE_DATA = "PERSISTENCE_DATA"


# execution_spec info
BASICJSONPERSISTENCE = "BASICJSONPERSISTENCE"  # primary key
SAVE_AT_EXIT = "SAVE_AT_EXIT"  # True/False
CREATE_FOLDER = "CREATE_FOLDER"  # True/False
FILEPATH = "FILEPATH"  # "....json" filename

