
# execution nodes
CLEAR_BASICJSONPERSISTENCE = "CLEAR_BASICJSONPERSISTENCE"
RESET_BASICJSONPERSISTENCE = "RESET_BASICJSONPERSISTENCE"
READ_BASICJSONPERSISTENCE = "READ_BASICJSONPERSISTENCE"
READ_PERSISTENCE = "READ_PERSISTENCE"


# interfaces
PERSISTENCE_DATA = "PERSISTENCE_DATA"


# execution_spec info
BASICJSONPERSISTENCE = "BASICJSONPERSISTENCE"  # primary key
CREATE_FOLDER = "CREATE_FOLDER"  # True/False
FOLDERPATH = "FOLDERPATH"  # path to folder (can use "." or "~")
FILENAME = "FILENAME"  # "....json" filename

