site_name: chassis2024 Documentation

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      primary: teal
      accent: purple

nav:
  - 'Chassis 2024': 'index.md'
  - 'Tutorial':
    - 'Ex #1: Hello, world!': 'ex_10_helloworld.md'
    - 'Ex #2: Echo': 'ex_20_echo.md'
    - 'Ex #3: Echo 2': 'ex_30_echo2.md'
